return {
  settings = {
    yaml = {
      format = { enable = true },
      customTags = {
        '!And sequence',
        '!And',
        '!Base64',
        '!Cidr',
        '!Equals sequence',
        '!Equals',
        '!FindInMap sequence',
        '!FindInMap',
        '!GetAZs',
        '!GetAtt',
        '!If sequence',
        '!If',
        '!ImportValue sequence',
        '!ImportValue',
        '!Join sequence',
        '!Join',
        '!Not sequence',
        '!Not',
        '!Or sequence',
        '!Or',
        '!Ref',
        '!Select sequence',
        '!Select',
        '!Split sequence',
        '!Split',
        '!Sub sequence',
        '!Sub',
      },
    },
  },
}
